"""Add notification expiration and deletion fields

Revision ID: 62fadf502813
Revises: e6a3b63766a0
Create Date: 2025-09-16 15:45:58.105119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fadf502813'
down_revision = 'e6a3b63766a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'deleted_at')
    op.drop_column('notifications', 'expires_at')
    # ### end Alembic commands ###
