"""Add created_via field to products

Revision ID: 74abc36ad6e9
Revises: afa3d6ece52d
Create Date: 2025-09-05 16:51:27.371880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74abc36ad6e9'
down_revision = 'afa3d6ece52d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_important'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_read'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_updated_at'), table_name='messages')
    
    # Add created_via column as nullable first
    op.add_column('products', sa.Column('created_via', sa.String(length=20), nullable=True))
    
    # Update existing products to have created_via = 'admin_web' (assuming they were created via admin web)
    op.execute("UPDATE products SET created_via = 'admin_web' WHERE created_via IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('products', 'created_via', nullable=False)
    
    op.drop_index(op.f('idx_products_faculty'), table_name='products')
    op.create_index(op.f('ix_products_faculty'), 'products', ['faculty'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_faculty'), table_name='products')
    op.create_index(op.f('idx_products_faculty'), 'products', ['faculty'], unique=False)
    op.drop_column('products', 'created_via')
    op.create_index(op.f('ix_messages_updated_at'), 'messages', ['updated_at'], unique=False)
    op.create_index(op.f('ix_messages_message_type'), 'messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_messages_is_read'), 'messages', ['is_read'], unique=False)
    op.create_index(op.f('ix_messages_is_important'), 'messages', ['is_important'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###
