"""Add discontinued field to products

Revision ID: e6a3b63766a0
Revises: 74abc36ad6e9
Create Date: 2025-09-05 17:05:53.885238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a3b63766a0'
down_revision = '74abc36ad6e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discontinued', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discontinued')
    # ### end Alembic commands ###
